language: objective-c  
osx_image: xcode10.1
xcode_project: Filantropia.xcodeproj
xcode_scheme: Filantropia
xcode_sdk: iphonesimulator12.1
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X

